ncp:
  storage:
    bucket:
      folder:
        item-post: ${LOCAL_NCP_STORAGE_FOLDER_ITEM_POST}
        user-profile: ${LOCAL_NCP_STORAGE_FOLDER_USER_PROFILE}

spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/${LOCAL_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true
    ##url: jdbc:mysql://localhost:3306/${LOCAL_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    ##driver-class-name: com.mysql.cj.jdbc.Driver

    # 테스트
    hikari:
      maximum-pool-size: 30       # 여기를 늘리면 됨 (기본 10)
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 10000
      leak-detection-threshold: 5000  #  커넥션 점유 10초 이상이면 로그 출력

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${LOCAL_NAVER_CLIENT_ID}
            client-secret: ${LOCAL_NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost:8000/login/oauth2/code/naver

server:
  servlet:
    session:
      timeout: 30m  # 세션 유지 시간 설정 (추후)

logging:
  level:
    root: INFO
    com.swyp.artego: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
