name: Pull Request Workflow (docker build test)

on:
  pull_request:
    branches:
      - main
      - dev
      - temp

jobs:
  docker-build-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Docker Build Test Only (no login)
        run: |
          docker build -t temp-pr-check .